[workspace]
resolver = "2"
members = [
    "src/cli",
    "src/daemon",
    "src/lib",
    "src/derive",
    "src/plugin-demo",
    "src/plugin-wifi",
    "src/plugin-ovs",
]

[workspace.package]
version = "0.1.0"
authors = ["Gris Ge"]
description = "Linux Network Management Tool"
documentation = "https://gitlab.freedesktop.org/NetworkManager/NetworkManager/"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.89"

[workspace.dependencies]
nipart = { version = "0.1.0", path = "src/lib" }
mudz = { git = "https://github.com/cathay4t/mudz.git" }
serde = { version = "1.0.144", features = ["derive"] }
env_logger = "0.11.0"
log = "0.4.17"
serde_json = "1.0.87"
rmsd_yaml = "0.1.0"
uuid = { version = "1.6.1", default-features = false, features = ["std", "v7"] }
futures-util = "0.3.11"
futures-channel = "0.3.11"
rand = "0.9"
clap = { version = "4.5", features = [ "cargo"] }
wl-nl80211 = "0.7.0"
shuli = { git = "https://github.com/cathay4t/shuli.git" }
syn = { version = "3.0", default-features = false, features = [ "derive" ] }
quote = "1.0"

[workspace.dependencies.tokio]
version ="1.35.0"
features = ["net", "io-util", "rt", "rt-multi-thread", "macros", "sync", "time", "fs", "signal"]

[workspace.dependencies.nix]
version = "0.31.0"
default-features = false
features = ["feature", "hostname", "socket"]


[workspace.dependencies.nispor]
git = "https://github.com/nispor/nispor"

[workspace.dependencies.mozim]
version = "0.3.2"
default-features = false

[workspace.dependencies.rtnetlink]
git = "https://github.com/rust-netlink/rtnetlink"

[workspace.dependencies.unicode-width]
version = "0.2.2"

[patch.crates-io]
rtnetlink = { git = "https://github.com/rust-netlink/rtnetlink" }
netlink-packet-route = { git = "https://github.com/rust-netlink/netlink-packet-route" }
